### ISSUE TITLE
[FEATURE REQUEST] Not working in canvas

### ISSUE THREAD

**Issue by Gourav1910** [pvojtechovsky/obsidian-link-with-alias#14]
Hi your plugin is working fine in notes but not working canvas cards. If possible please update it because I write most of my notes in canvas cards and then later convert it into notes if required.

**Comment by pvojtechovsky** [comment]
I checked why it doesn't work. The reason is that Canvas Card has no file and therefore the code which should create a new note in the same folder doesn't work ... and there is a check which skips whole link feature because of that. I am trying to detect the file path of the parent canvas file, but I failed till now. In worst case I will hack it and the new files linked from canvas Card will be created in the root folder of the vault.

**Comment by pvojtechovsky** [comment]
The feature was implemented in release 1.0.7
